config/routes.rb
Rails.application.routes.draw do

  resources :build_logs
  resources :annotations
  resources :submission_configs
  devise_for :users

  root 'start#index'

  get 'info',      to: 'start#info'
  get 'notfound',  to: 'start#notfound'


  match 'preferences' => 'preferences#edit', :as => :preferences, via: [:get, :patch]

  get 'bomb',        to: 'application#bomb'
  post 'report_csp', to: 'application#report_csp'

  # settings
  get   'settings',  to: 'start#settings'

  # profile
  get   'edit_profile',    to: 'start#edit_profile'
  patch 'update_profile',  to: 'start#update_profile'

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'


  resources :pages, only: [:show]
  
  resources :iconsets do
    resources :icons, only: [:edit, :destroy, :update]
  end

  resources :import_mappings, only: [:new, :create, :show] do
    post :apply_mapping, on: :member
    get :import_preview, on: :member
  end

  resources :maps do
    member do
      get :import
      post :import_preview
      post :importing
    end
    resources :tags, only: [:index, :show]
    resources :relations
    resources :people
    resources :layers do
      collection do
        post :search
        get :fetch_layers, to: 'layers#fetch_layers'
      end
      member do
        get :pack
        patch :build
        get :annotations
        get :relations
        get :images
        get :import
        post :import_preview
        post :importing
      end
      resources :places do
        resources :images
        resources :videos
        member do
          delete :delete_image_attachment
          post :sort
          get :clone
          get :edit_clone
          patch :update_clone
        end
      end
    end
  end

  namespace :admin do
    resources :users
    resources :groups
    resources :pages
  end

  scope "/:locale" do
    scope "/:layer_id" do
      resources :submissions, :controller => "public/submissions", only: [:new, :create, :edit, :update, :index] do
        get :new_place, :controller => "public/submissions", :action => 'new_place'
        post :create_place, :controller => "public/submissions", :action => 'create_place'
        scope "/:place_id" do
          get :edit_place, :controller => "public/submissions", :action => 'edit_place'
          patch :update_place, :controller => "public/submissions", :action => 'update_place'
          get :new_image, :controller => "public/submissions", :action => 'new_image'
          post :create_image, :controller => "public/submissions", :action => 'create_image'
          get :finished, :controller => "public/submissions", :action => 'finished'
        end
      end
    end
  end

  namespace :public do
    resources :maps, only: [:show, :allplaces, :index], :defaults => { :format => :json } do
      resources :layers, only: [:show], :defaults => { :format => :json } do
        resources :places, only: [:show], :defaults => { :format => :json }
      end
      resources :tags, only: [:index], :defaults => { :format => :json }
      member do
        get :allplaces
      end

    end
  end
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  belongs_to :map
  has_many :annotations, dependent: :restrict_with_error

  validates :name, presence: true
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :set_person, only: %i[edit update destroy]

  # GET /people or /people.json
  def index
    @map = Map.sorted.by_user(current_user).friendly.find(params[:map_id])
    @people = @map.people
  end

  def new
    @map = Map.sorted.by_user(current_user).friendly.find(params[:map_id])
    @person = Person.new
  end

  def edit; end

  def create
    @map = Map.sorted.by_user(current_user).friendly.find(params[:map_id])
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to map_people_url(@map), notice: 'Person was successfully created.' }
        format.json { render :index, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to map_people_url(@map), notice: 'Person was successfully updated.' }
        format.json { render :index, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @person.destroy
      respond_to do |format|
        format.html { redirect_to map_people_url(@map), notice: 'Person was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to map_people_url(@map), notice: 'Person could not be destroyed, since its connected to 1 or more annotations.' }
      end
    end
  end

  private

  def set_person
    @map = Map.sorted.by_user(current_user).friendly.find(params[:map_id])
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, :info, :map_id)
  end
end

app/views/people/_form.html.haml
= simple_form_for([@map,@person]) do |f|
  .grid-x
    .large-12.cell
      = f.error_notification
  .grid-x
    .large-3.cell
      &nbsp;
    .large-6.medium-12.cell
      .form-inputs
        = f.input :name
        = f.association :map, as: :hidden, :input_html => { :value => @map.id }
        = f.input :info
      .form-actions
        = f.button :submit, :class => "button"
    .large-3.cell
      &nbsp;

app/views/people/edit.html.haml
#form-wrapper.large-wrapper
  %p.text-right.close_link_wrapper
    =link_to map_path(@map), :class=>'close_link' do
      %i.fi.fi-x
  %p.small
    %a{:href => map_path(@map), :title => 'Settings'}
      %i.fi-map.fi-21
      Map
    \&mdash;
    %a{:href => map_people_path(@map), :title => 'Iconsets'}
      %i.fi-marker.fi-21
      People

  %h1 Editing person

  = render 'form'


  %hr
  = link_to 'All people', map_people_path(@map), :class => 'button'

app/views/people/index.html.haml
- content_for(:title) { "People" }

#table-wrapper
  %h1
    Map:
    = link_to map_path(@map) do
      = @map.title
    = link_to edit_map_path(@map) do
      %i.fi-pencil.fi-24
  %h2 People
  %p.text-right
    = link_to new_map_person_path(@map), :class=>'button tiny' do
      %i.fi-plus.fi-18
      Add Person
  %table
    %thead
      %tr
        %th Name
        %th Annotations?
        %th Actions
        %th

    %tbody
      - @people.each do |person|
        %tr
          %td
            = person.name
            %br
            = person.info
          %td
            - if person.annotations.count > 0
              - person.annotations.each do |annotate|
                = link_to map_layer_place_path(annotate.place.layer.map,annotate.place.layer,annotate.place) do
                  = annotate.id
          %td= link_to 'Edit', edit_map_person_path(@map,person)
          %td
            - if admin?
              = link_to 'Destroy', map_person_path(@map,person), method: :delete, data: { confirm: 'Are you sure?' }

  %p.text-right
    = link_to new_map_person_path(@map), :class=>'button tiny' do
      %i.fi-plus.fi-18
      Add Person

app/views/people/new.html.haml
#form-wrapper.large-wrapper
  %p.text-right.close_link_wrapper
    =link_to map_path(@map), :class=>'close_link' do
      %i.fi.fi-x
  %p.small
    %a{:href => map_path(@map), :title => 'Settings'}
      %i.fi-map.fi-21
      Map
    \&mdash;
    %a{:href => map_people_path(@map), :title => 'Iconsets'}
      %i.fi-marker.fi-21
      People

  %h1 New person

  = render 'form'



  %hr
  = link_to 'All people', map_people_path(@map), :class => 'button'