config/routes.rb
Rails.application.routes.draw do

  resources :build_logs
  resources :annotations
  resources :submission_configs
  devise_for :users

  root 'start#index'

  get 'info',      to: 'start#info'
  get 'notfound',  to: 'start#notfound'


  match 'preferences' => 'preferences#edit', :as => :preferences, via: [:get, :patch]

  get 'bomb',        to: 'application#bomb'
  post 'report_csp', to: 'application#report_csp'

  # settings
  get   'settings',  to: 'start#settings'

  # profile
  get   'edit_profile',    to: 'start#edit_profile'
  patch 'update_profile',  to: 'start#update_profile'

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'


  resources :pages, only: [:show]
  
  resources :iconsets do
    resources :icons, only: [:edit, :destroy, :update]
  end

  resources :import_mappings, only: [:new, :create, :show] do
    post :apply_mapping, on: :member
    get :import_preview, on: :member
  end

  resources :maps do
    member do
      get :import
      post :import_preview
      post :importing
    end
    resources :tags, only: [:index, :show]
    resources :relations
    resources :people
    resources :layers do
      collection do
        post :search
        get :fetch_layers, to: 'layers#fetch_layers'
      end
      member do
        get :pack
        patch :build
        get :annotations
        get :relations
        get :images
        get :import
        post :import_preview
        post :importing
      end
      resources :places do
        resources :images
        resources :videos
        member do
          delete :delete_image_attachment
          post :sort
          get :clone
          get :edit_clone
          patch :update_clone
        end
      end
    end
  end

  namespace :admin do
    resources :users
    resources :groups
    resources :pages
  end

  scope "/:locale" do
    scope "/:layer_id" do
      resources :submissions, :controller => "public/submissions", only: [:new, :create, :edit, :update, :index] do
        get :new_place, :controller => "public/submissions", :action => 'new_place'
        post :create_place, :controller => "public/submissions", :action => 'create_place'
        scope "/:place_id" do
          get :edit_place, :controller => "public/submissions", :action => 'edit_place'
          patch :update_place, :controller => "public/submissions", :action => 'update_place'
          get :new_image, :controller => "public/submissions", :action => 'new_image'
          post :create_image, :controller => "public/submissions", :action => 'create_image'
          get :finished, :controller => "public/submissions", :action => 'finished'
        end
      end
    end
  end

  namespace :public do
    resources :maps, only: [:show, :allplaces, :index], :defaults => { :format => :json } do
      resources :layers, only: [:show], :defaults => { :format => :json } do
        resources :places, only: [:show], :defaults => { :format => :json }
      end
      resources :tags, only: [:index], :defaults => { :format => :json }
      member do
        get :allplaces
      end

    end
  end
end

app/models/video.rb
# frozen_string_literal: true

class Video < ApplicationRecord
  belongs_to :place

  has_one_attached :file
  delegate_missing_to :file

  has_one_attached :filmstill
  delegate_missing_to :filmstill

  validates :title, presence: true
  validate :check_file_presence
  validate :check_file_format

  scope :sorted, -> { order(sorted: :asc) }
  scope :sorted_by_place, ->(place_id) { where(place_id: place_id).order(sorted: :asc) }
  scope :preview, ->(place_id) { where(place_id: place_id, preview: true) }

  def video_url
    ApplicationController.helpers.video_url(file)
  end

  def video_linktag
    ApplicationController.helpers.video_linktag(file, filmstill)
  end

  private

  def check_file_presence
    errors.add(:file, 'no file present') unless file
  end

  def check_file_format
    errors.add(:file, 'format must be MP4') if file.attached? && !file.content_type.in?(%w[video/mp4 application/mp4])
  end
end

app/controllers/videos_controller.rb
# frozen_string_literal: true

class VideosController < ApplicationController
  before_action :set_video, only: %i[show edit update destroy]

  # GET /videos
  # GET /videos.json
  def index
    @place = Place.where(id: params[:place_id]).first
    redirect_to root_url, notice: 'No place defined for showing this video' if !@place || @place.layer.map.group != current_user.group
    @videos = Video.where(place_id: @place_id)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    redirect_to root_url, notice: "You are not allowed for viewing this video #{current_user.group.title}" if @video.place.layer.map.group != current_user.group && current_user.group.title != 'Admins'
  end

  # GET /videos/new
  def new
    @video = Video.new
    @map = Map.by_user(current_user).friendly.find(params[:map_id])
    @layer = Layer.friendly.find(params[:layer_id])
    @place = Place.find(params[:place_id])
    redirect_to root_url, notice: 'No place defined for adding an video' unless @place || (@place && @place.layer.map.group == current_user.group)
  end

  # GET /videos/1/edit
  def edit
    @place = @video.place
    redirect_to root_url, notice: 'No valid place defined for editing an mage' unless @place || (@place && @place.layer.map.group == current_user.group)
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @map = Map.by_user(current_user).find(params[:map_id])
    @layer = Layer.find(params[:layer_id])
    @place = Place.find(params[:place_id])
    respond_to do |format|
      if @video.save
        format.html { redirect_to edit_map_layer_place_path(@video.place.layer.map, @video.place.layer, @video.place), notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to edit_map_layer_place_path(@video.place.layer.map, @video.place.layer, @video.place), notice: 'Video was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to edit_map_layer_place_path(@video.place.layer.map, @video.place.layer, @video.place), notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_video
    @map = Map.by_user(current_user).where(id: params[:map_id]).first
    @layer = Layer.find(params[:layer_id])
    @place = Place.find(params[:place_id])
    @video = Video.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def video_params
    params.require(:video).permit(:title, :licence, :source, :creator, :place_id, :alt, :caption, :sorting, :preview, :file)
  end
end

app/helpers/videos_helper.rb
# frozen_string_literal: true

module VideosHelper
  def video_url(file)
    return unless file.attached?

    polymorphic_url(file)
  end

  def video_linktag(file, filmstill, _title = '')
    return unless file.attached?

    if filmstill&.attached?
      video_tag(polymorphic_url(file).to_s, controls: true, preload: 'metadata', poster: polymorphic_url(filmstill).to_s, poster_skip_pipeline: true)
    else
      video_tag(polymorphic_url(file).to_s, controls: true, preload: 'metadata')
    end
  end
end

app/views/videos/_form.html.haml
= simple_form_for([@map,@layer,@place,@video]) do |f|
  .grid-x
    .large-12.cell
      = f.error_notification
      = f.association :place, as: :hidden, :input_html => { :value => @place.id }

  .grid-x
    .large-2.cell
      &nbsp;
    .large-8.medium-12.cell
      .form-inputs
        = f.input :title
        %hr
        .grid-x.grid-padding-x
          .large-6.medium-6.cell
            = f.input :file, as: :file, input_html: { accept: ('video'), multiple: false }, label: "Video (MP4)"
            - if params[:action] == 'edit' && @video.file.attached?
              = link_to url_for(@video.file) do
                = video_tag url_for(@video.file)
            %p.shy
              Please check that your Video is not larger than 2000px
          .large-6.medium-6.cell
            .grid-x.grid-padding-x
              .large-7.medium-7.cell
                #switch.switch.inline.hide
                  %label Preview?
                  %input{:name=>"video[preview]", :class => "switch-input", :id => "video_preview", :type => "checkbox", :checked => @video.preview }
                  %label.switch-paddle{:for=>"video_preview"}
                    %span.show-for-sr
                      Preview
                    %span.switch-active{:aria-hidden=>"true"} Preview
                    %span.switch-inactive{:aria-hidden=>"true"} Preview
                %p.shy.hide Show this video in the popup and in listings?
              .large-5.medium-5.cell
                = f.input :sorting, size: 4
                %p.shy Sorting order (1-99)


        %hr
        .grid-x.grid-padding-x
          .large-6.medium-6.cell
            = f.input :creator
            %p.shy Who is the creator (director, camera, animator,...) of this video?
            = f.input :licence
            %p.shy Under which licence the video is and/or shall be published? (CC, Public Domain, Rights reserved)
            = f.input :source
            %p.shy Origin of this video
          .large-6.medium-6.cell
            = f.input :alt, label: "Alternate Text"
            %p.shy Please provide a short description for screenreader

            = f.input :caption
            %p.shy Do you want to add a caption?


      .form-actions
        = f.button :submit, :class => "button"
    .large-2.cell
      &nbsp;

app/views/videos/edit.html.haml
#form-wrapper
	%h1 Editing video
	%p
		Edit this video for

		%strong
			#{@place.layer.map.title}
		\>
		%strong
			#{@place.layer.title}
		\>
		%strong
			#{@place.title}

	= render 'form'

	= link_to map_layer_place_video_path(@place.layer.map,@place.layer,@place,@video), method: :delete, data: { confirm: 'Are you sure to delete this video?' }, :class => 'button warning' do
		%i.fi.fi-trash
		Delete
	&nbsp;
	= link_to edit_map_layer_place_path(@place.layer.map,@place.layer,@place), class: "button"  do
		Back to place

app/views/videos/index.html.haml
#table-wrapper

  %h1 Videos

  %table
    %thead
      %tr
        %th Video
        %th Metadata
        %th Sorting + Preview?
        %th

    %tbody
      - @videos.each do |video|
        %tr
          %td.img_col{style: 'width: 200px'}
            %p.shy
              =link_to map_layer_place_path(video.place.layer.map.id,video.place.layer.id,video.place.id) do
                = video.place.title
            - if video.title.present?
              %h4
                = video.title
            - elsif video.file.attached?
              %p
                %tt= video.file.filename
            - else
              %h4
                No Name
            - if video.file.attached?
              = link_to url_for(video.file) do
                = video_tag url_for(video.file)
            = video.alt
            %br
            = video.caption
          %td
            - if video.creator.present?
              %strong Creator:
              = video.creator
              %br
            - if video.licence.present?
              %strong Licence:
              = video.licence
              %br
            - if video.source.present?
              %string Source
              = video.source
            - if video.preview
              Previewvideo
              %i.fi-star.fi-24
            = video.sorting
          %td
            = link_to edit_map_layer_place_video_path(video.place.layer.map,video.place.layer,video.place,video), :class => 'button' do
              %i.fi.fi-pencil
              Edit
            = link_to map_layer_place_video_path(video.place.layer.map,video.place.layer,video.place,video), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button warning' do
              %i.fi.fi-x
              Destroy

app/views/videos/new.html.haml
#form-wrapper
	%h1 New video

	%p
		Add an video for

		%strong
			#{@place.layer.map.title}
		\>
		%strong
			#{@place.layer.title}
		\>
		%strong
			#{@place.title}


	= render 'form'

	= link_to 'Back to place', edit_map_layer_place_path(@place.layer.map,@place.layer,@place), class: 'button secondary'

app/views/videos/show.html.haml
#form-wrapper
  %p#notice= notice
  %p
    - if @video.file.attached?
      = link_to url_for(@video.file) do
        = video_tag url_for(@video.file), controls: true
    - else
      No Video
  %p
    %b Place:
    = link_to map_path(@video.place.layer.map) do
      = @video.place.layer.map.title
    \>
    = link_to map_layer_path(@video.place.layer.map,@video.place.layer) do
      = @video.place.layer.title
    \>
    = link_to map_layer_place_path(@video.place.layer.map,@video.place.layer,@video.place)  do
      = @video.place.title

  - if @video.title
    %h3= @video.title
  .card.card-video-info
    %p
      - if @video.file.attached?
        %b File:
        = link_to url_for(@video.file) do
          %tt= @video.file.filename
    - if @video.alt.present?
      %p
        %b Alt:
        = @video.alt
    - if @video.caption.present?
      %p
        %b Caption:
        = @video.caption
    - if @video.source.present?
      %p
        %b Source:
        = link_to @video.source do
          = @video.source
    %p
      %b Creator:
      - if @video.creator.present?
        = @video.creator
      - else
        Unknown
      \|
      %b Licence:
      - if @video.licence.present?
        = @video.licence
      - else
        Unknown
    %p
      - if @video.sorting.present?
        %b Sorting:
        = @video.sorting
      - if @video.sorting.present? && @video.preview.present?
        \|
      - if @video.preview
        %b Preview:
        %i.fi-star.fi-24

  = link_to edit_map_layer_place_video_path(@place.layer.map,@place.layer,@place,@video), class: "button"  do
    %i.fi.fi-pencil
    Edit
  &nbsp;
  = link_to map_layer_place_video_path(@place.layer.map,@place.layer,@place,@video), method: :delete, data: { confirm: 'Are you sure to delete this video?' }, :class => 'button warning' do
    %i.fi.fi-trash
    Delete
  &nbsp;
  = link_to edit_map_layer_place_path(@place.layer.map,@place.layer,@place), class: "button"  do
    Back to place