config/routes.rb
Rails.application.routes.draw do

  resources :build_logs
  resources :annotations
  resources :submission_configs
  devise_for :users

  root 'start#index'

  get 'info',      to: 'start#info'
  get 'notfound',  to: 'start#notfound'


  match 'preferences' => 'preferences#edit', :as => :preferences, via: [:get, :patch]

  get 'bomb',        to: 'application#bomb'
  post 'report_csp', to: 'application#report_csp'

  # settings
  get   'settings',  to: 'start#settings'

  # profile
  get   'edit_profile',    to: 'start#edit_profile'
  patch 'update_profile',  to: 'start#update_profile'

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'


  resources :pages, only: [:show]
  
  resources :iconsets do
    resources :icons, only: [:edit, :destroy, :update]
  end

  resources :import_mappings, only: [:new, :create, :show] do
    post :apply_mapping, on: :member
    get :import_preview, on: :member
  end

  resources :maps do
    member do
      get :import
      post :import_preview
      post :importing
    end
    resources :tags, only: [:index, :show]
    resources :relations
    resources :people
    resources :layers do
      collection do
        post :search
        get :fetch_layers, to: 'layers#fetch_layers'
      end
      member do
        get :pack
        patch :build
        get :annotations
        get :relations
        get :images
        get :import
        post :import_preview
        post :importing
      end
      resources :places do
        resources :images
        resources :videos
        member do
          delete :delete_image_attachment
          post :sort
          get :clone
          get :edit_clone
          patch :update_clone
        end
      end
    end
  end

  namespace :admin do
    resources :users
    resources :groups
    resources :pages
  end

  scope "/:locale" do
    scope "/:layer_id" do
      resources :submissions, :controller => "public/submissions", only: [:new, :create, :edit, :update, :index] do
        get :new_place, :controller => "public/submissions", :action => 'new_place'
        post :create_place, :controller => "public/submissions", :action => 'create_place'
        scope "/:place_id" do
          get :edit_place, :controller => "public/submissions", :action => 'edit_place'
          patch :update_place, :controller => "public/submissions", :action => 'update_place'
          get :new_image, :controller => "public/submissions", :action => 'new_image'
          post :create_image, :controller => "public/submissions", :action => 'create_image'
          get :finished, :controller => "public/submissions", :action => 'finished'
        end
      end
    end
  end

  namespace :public do
    resources :maps, only: [:show, :allplaces, :index], :defaults => { :format => :json } do
      resources :layers, only: [:show], :defaults => { :format => :json } do
        resources :places, only: [:show], :defaults => { :format => :json }
      end
      resources :tags, only: [:index], :defaults => { :format => :json }
      member do
        get :allplaces
      end

    end
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  def index
    @map = Map.by_user(current_user).friendly.find(params[:map_id])
    @tags = @map.places.all_tags
  end

  def show
    @map = Map.by_user(current_user).friendly.find(params[:map_id])
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @places = Place.tagged_with(@tag.name)
  end
end

app/views/tags/index.html.haml
- content_for(:title) { "Tags of #{@map.title}" }

#table-wrapper
  %p.text-right.close_link_wrapper
    =link_to map_path(@map), :class=>'close_link' do
      %i.fi.fi-x
  %h3
    = link_to map_path(@map) do
      = @map.title
    > Tags

  - @tags.each do |tag|
    %span.label.secondary.tag
      = link_to map_tag_path(@map,tag) do
        %i.fi-price-tag
        = tag.name
        (#{@map.places.tagged_with(["#{tag.name}"]).count})
    %ul.hide
      - @map.places.tagged_with(["#{tag.name}"]).each do |place|
        %li
          - if place.startdate.present?
            %p
              = smart_date_display(place.startdate, place.enddate)
          %h5
            = link_to map_layer_place_path(@map,place.layer,place) do
              = place.title

app/views/tags/show.html.haml
- content_for(:title) { "#{@tag.name}" }


#table-wrapper
  %h3
    = link_to map_path(@map) do
      = @map.title
    \:
    = link_to map_tags_path(@map) do
      = @tag.name

  %p.hint.text-left
    #{@map.places.tagged_with(["#{@tag.name}"]).count} place(s) tagged with #{@tag.name}
  %hr
  %div
    - @map.places.tagged_with(["#{@tag.name}"]).each do |place|
      %div.cards
        - if place.startdate.present?
          %p
            = smart_date_display(place.startdate, place.enddate)
        %h5
          = link_to map_layer_place_path(@map,place.layer,place) do
            = place.title
        %p.small
          = link_to map_layer_path(@map,place.layer) do
            = place.layer.title
        - if place.tag_list
          %p
            - place.tags.each do |tag|
              %span.label.secondary.tag
                %i.fi-price-tag
                = link_to map_tag_path(@map,tag) do
                  = tag
  %hr
  %p
    = link_to map_tags_path(@map), class: "button small" do
      %i.fi-pricetag-multiple
      List of all tags
    &nbsp;
    = link_to map_layers_path(@map), class: "button small" do
      List of all layers