config/routes.rb
Rails.application.routes.draw do

  resources :build_logs
  resources :annotations
  resources :submission_configs
  devise_for :users

  root 'start#index'

  get 'info',      to: 'start#info'
  get 'notfound',  to: 'start#notfound'


  match 'preferences' => 'preferences#edit', :as => :preferences, via: [:get, :patch]

  get 'bomb',        to: 'application#bomb'
  post 'report_csp', to: 'application#report_csp'

  # settings
  get   'settings',  to: 'start#settings'

  # profile
  get   'edit_profile',    to: 'start#edit_profile'
  patch 'update_profile',  to: 'start#update_profile'

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'


  resources :pages, only: [:show]
  
  resources :iconsets do
    resources :icons, only: [:edit, :destroy, :update]
  end

  resources :import_mappings, only: [:new, :create, :show] do
    post :apply_mapping, on: :member
    get :import_preview, on: :member
  end

  resources :maps do
    member do
      get :import
      post :import_preview
      post :importing
    end
    resources :tags, only: [:index, :show]
    resources :relations
    resources :people
    resources :layers do
      collection do
        post :search
        get :fetch_layers, to: 'layers#fetch_layers'
      end
      member do
        get :pack
        patch :build
        get :annotations
        get :relations
        get :images
        get :import
        post :import_preview
        post :importing
      end
      resources :places do
        resources :images
        resources :videos
        member do
          delete :delete_image_attachment
          post :sort
          get :clone
          get :edit_clone
          patch :update_clone
        end
      end
    end
  end

  namespace :admin do
    resources :users
    resources :groups
    resources :pages
  end

  scope "/:locale" do
    scope "/:layer_id" do
      resources :submissions, :controller => "public/submissions", only: [:new, :create, :edit, :update, :index] do
        get :new_place, :controller => "public/submissions", :action => 'new_place'
        post :create_place, :controller => "public/submissions", :action => 'create_place'
        scope "/:place_id" do
          get :edit_place, :controller => "public/submissions", :action => 'edit_place'
          patch :update_place, :controller => "public/submissions", :action => 'update_place'
          get :new_image, :controller => "public/submissions", :action => 'new_image'
          post :create_image, :controller => "public/submissions", :action => 'create_image'
          get :finished, :controller => "public/submissions", :action => 'finished'
        end
      end
    end
  end

  namespace :public do
    resources :maps, only: [:show, :allplaces, :index], :defaults => { :format => :json } do
      resources :layers, only: [:show], :defaults => { :format => :json } do
        resources :places, only: [:show], :defaults => { :format => :json }
      end
      resources :tags, only: [:index], :defaults => { :format => :json }
      member do
        get :allplaces
      end

    end
  end
end

app/models/place.rb
# frozen_string_literal: true

require 'csv'

class Place < ApplicationRecord
  belongs_to :layer
  belongs_to :icon, optional: true

  acts_as_taggable_on :tags

  has_one_attached :audio, dependent: :destroy

  has_many :relations_tos, foreign_key: 'relation_to_id',
                           class_name: 'Relation',
                           dependent: :destroy
  has_many :relations_froms, foreign_key: 'relation_from_id',
                             class_name: 'Relation',
                             dependent: :destroy
  has_many :annotations
  accepts_nested_attributes_for :relations_tos, allow_destroy: true
  accepts_nested_attributes_for :relations_froms, allow_destroy: true
  accepts_nested_attributes_for :annotations, reject_if: ->(a) { a[:title].blank? }, allow_destroy: true

  has_many :images, dependent: :destroy
  has_many :videos, dependent: :destroy
  has_many :submissions, dependent: :destroy

  validate :check_audio_format
  validates :title, presence: true
  validates :lat, presence: true, format: { with: /\A-?\d+(\.\d+)?\z/, message: 'should be a valid latitude value' }
  validates :lon, presence: true, format: { with: /\A-?\d+(\.\d+)?\z/, message: 'should be a valid longitude value' }
  validates :lat, presence: true, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }
  validates :lon, presence: true, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }

  validates_uniqueness_of :id

  scope :sorted_by_startdate, -> { order(startdate: :asc) }
  scope :sorted_by_title, -> { order(title: :asc) }

  scope :published, -> { where(published: true) }

  attr_accessor :startdate_date, :startdate_time, :enddate_date, :enddate_time

  after_initialize :sensitive_location
  attribute :public_lat
  attribute :public_lon

  before_save do
    if startdate_date.present? && startdate_time.present?
      self.startdate = "#{startdate_date} #{startdate_time}"
    elsif startdate_date.present?
      self.startdate = "#{startdate_date} 00:00:00"
    # nil from factories, blank from post request
    elsif startdate_date.nil? || startdate_date.blank?
      self.startdate = nil
    end
    if enddate_date.present? && enddate_time.present?
      self.enddate = "#{enddate_date} #{enddate_time}"
    elsif enddate_date.present?
      self.enddate = "#{enddate_date} 00:00:00"
    elsif enddate_date.nil? || startdate_date.blank?
      self.enddate = nil
    end

    clean_text_fields
  end

  def self.all_unique_tags
    ActsAsTaggableOn::Tag.joins(:taggings)
                         .where(taggings: { taggable_type: 'Place' })
                         .distinct
  end

  def title_and_location
    if location.blank?
      title
    else
      "#{title} (#{location})"
    end
  end

  def title_subtitle_and_location
    if location.blank?
      title
    elsif !subtitle.blank?
      "#{title} — #{subtitle} (#{location})"
    else
      "#{title} (#{location})"
    end
  end

  def sensitive_location
    if sensitive
      locs = random_loc(long: read_attribute(:lon), lat: read_attribute(:lat), radius_meters: read_attribute(:sensitive_radius))
      self.public_lon = locs[0].to_s
      self.public_lat = locs[1].to_s
    else
      self.public_lat = read_attribute(:lat)
      self.public_lon = read_attribute(:lon)
    end
  end

  def random_loc(long:, lat:, radius_meters:)
    u = SecureRandom.random_number(1.0)
    v = SecureRandom.random_number(1.0)
    w = radius_meters / 111_300.0 * Math.sqrt(u)
    t = 2 * Math::PI * v
    x = w * Math.cos(t)
    y = w * Math.sin(t)
    [x + long.to_f, y + lat.to_f]
  end

  def layer_title
    layer.title
  end

  def layer_slug
    layer.title.parameterize
  end

  def layer_type
    layer.ltype
  end

  def color
    layer.color
  end

  def layer_color
    layer.color
  end

  def date
    ApplicationController.helpers.smart_date_display(startdate, enddate)
  end

  def date_with_qualifier
    if startdate_qualifier && enddate_qualifier && (startdate_qualifier != '' || enddate_qualifier != '')
      ApplicationController.helpers.smart_date_display_with_qualifier(startdate, enddate, startdate_qualifier, enddate_qualifier)
    else
      date
    end
  end

  def url
    ApplicationController.helpers.url(layer.map.slug, layer.slug, id)
  end

  def show_link
    ApplicationController.helpers.show_link(title, layer.map_id, layer.id, id)
  end

  def edit_link
    ApplicationController.helpers.edit_link(layer.map.id, layer.id, id)
  end

  def icon_name
    icon ? ApplicationController.helpers.icon_name(icon.title) : ''
  end

  def icon_link
    icon&.file&.attached? ? ApplicationController.helpers.icon_link(icon.file) : ''
  end

  def icon_class
    icon&.iconset&.class_name ? ApplicationController.helpers.icon_class(icon.iconset.class_name, icon.title) : ''
  end

  def imagelink2
    # used for on map display of the preview image
    # this call is very costly for larger datasets, maybe a switch in the map settings could be establied?
    # return '' unless images.exists?

    i = images.filter { |image| image.place_id == id && image.preview }
    i.any? ? ApplicationController.helpers.image_link(i.first) : ''
  end

  def audiolink
    ApplicationController.helpers.audio_link(audio) if audio
  end

  def full_address
    if location.present? && address.present?
      if location == address
        location
      else
        "#{location} #{address}"
      end
    elsif location.present?
      location
    else
      address
    end
  end

  def full_address_with_city
    c = ''
    c = ", #{zip} #{city}" if zip && city
    "#{full_address}#{c}"
  end

  def annotations_as_text
    t = ''
    return unless annotations&.count&.positive?

    annotations.each do |a|
      t = "#{t}#{a.person.name}:\n" if a.person
      t = "#{t}#{a.title}\n" if a.title
      t = "#{t}#{a.text.html_safe}\n"
      t += "---------------\n"
    end
    t.to_s
  end

  def teaser_as_text
    require 'nokogiri'
    Nokogiri::HTML(teaser).text
  end

  def text_as_text
    require 'nokogiri'
    Nokogiri::HTML(text).text
  end

  def self.to_csv
    attributes = %w[id title teaser_as_text text_as_text annotations_as_text startdate enddate public_lat public_lon location address zip city country]
    headers = %w[id title teaser text annotations startdate enddate lat lon location address zip city country]
    CSV.generate(headers: false, force_quotes: false, strip: true) do |csv|
      csv << headers
      all.each do |place|
        csv << attributes.map { |attr| place.send(attr) }
      end
    end
  end

  private

  def check_audio_format
    return unless audio.attached? && !audio.content_type.in?(%w[audio/mpeg audio/x-m4a audio/mp4])

    errors.add(:audio, 'Format must be MP3 or M4A')
    audio.purge
  end

  def clean_text_fields
    self.text = remove_4byte_characters(text) if text
  end

  def remove_4byte_characters(string)
    string.each_char.select { |char| char.bytesize < 4 }.join
  end
end

app/helpers/places_helper.rb
# frozen_string_literal: true

module PlacesHelper
  include Rails.application.routes.url_helpers

  def default_url_options
    { host: Rails.application.config_for(:settings).app_host, protocol: Rails.application.config_for(:settings).app_host_protocol }
  end

  def qualifier_for_select
    [['Exact date', 'exact'], ['Approx. date', 'circa']]
  end

  def app_config
    @app_config ||= Rails.application.config_for(:settings)
  end

  def url(map_slug, layer_slug, id)
    "#{app_config.app_host_protocol}://#{app_config.app_host}/maps/#{map_slug}/layers/#{layer_slug}/places/#{id}"
  end

  def show_link(title, map_id, layer_id, id)
    " <a href=\"/maps/#{map_id}/layers/#{layer_id}/places/#{id}\">#{title}</a>"
  end

  def edit_link(map_id, layer_id, id)
    " <a href=\"/maps/#{map_id}/layers/#{layer_id}/places/#{id}/edit\" class='edit_link'><i class='fi fi-pencil'></i></a>"
  end

  def add_new_entry_link(place)
    "/maps/#{place.layer.map.id}/layers/#{place.layer.id}/places/new?location=#{place.location}&address=#{place.address}&zip=#{place.zip}&city=#{place.city}&lat=#{place.lat}&lon=#{place.lon}"
  end

  def icon_link(file)
    "<img src=\"#{polymorphic_url(file)}\">"
  end

  def icon_class(klass_name, title)
    "icon_#{klass_name} icon_#{title.parameterize}"
  end

  def icon_name(title)
    title.to_s
  end

  def image_link(image)
    return unless image.file&.attached?

    begin
      if image.place.layer.rasterize_images && image.itype == 'image'
        polymorphic_url(image.file.variant(resize: '800x800', 'ordered-dither': 'h8x8a').processed)
      else
        polymorphic_url(image.file.variant(resize: '800x800').processed)
      end
    rescue Errno::ENOENT => e
      ''
    rescue ActiveStorage::FileNotFoundError => e
      ''
    end
  end

  def audio_link(audio)
    return '' unless audio.attached?

    audio_tag rails_blob_url(audio), autoplay: false, controls: true
  end
end

app/views/places/_form_edit_clone.html.haml
= simple_form_for([@map,@layer,@place]) do |f|
  .grid-x.grid-padding-x
    .large-6.medium-3.cell
      %h1 Clone place
    .large-6.medium-4.cell
      &nbsp;
  .grid-x.grid-padding-x
    .large-12.cell
      = f.error_notification
      - if @place.errors.full_messages.present?
        %ul.hide
          = @place.errors.full_messages.each do |item,msg|
            %li= item
      %p
        Place
        %strong "#{@place.title}"
        has been cloned from #{@place.layer.map.title}: #{@place.layer.title}:
      %p
        Please select a map and a layer!
      %div#layer_change
        %div.inline#map_selector
          = f.input :layer_id, collection: @maps, as: :grouped_select, group_method: :layers, group_label_method: :title, label_method: :title, selected: @place.layer


  %hr
  .grid-x
    .large-6.medium-6.small-12.cell
      .form-actions.text-right
        = f.button :submit, :class => "button"

app/views/places/edit.html.haml
- content_for(:title) { "#{@place.title} (Edit)" }

#form-wrapper.large-wrapper{:data => { 'url' => "/maps/#{@map.id}/layers/#{@layer.id}/places/#{@place.id}.json", 'map_id' => "#{@map.id}", 'layer_id' => "#{@layer.id}", 'lat' => @place.lat, 'lon' => @place.lon, 'action' => 'edit' }}
  = link_to map_layer_url(@map,@layer), :class=>"close-button small", "aria-label"=>"Close back",:type=>"button" do
    %span{"aria-hidden"=>"true"}
      %i.fi.fi-x.fi-30
  = render 'form'

app/views/places/edit_clone.html.haml
- content_for(:title) { "#{@place.title} (Edit)" }

#form-wrapper.large-wrapper{:data => { 'url' => "/maps/#{@map.id}/layers/#{@layer.id}/places/#{@place.id}.json", 'map_id' => "#{@map.id}", 'layer_id' => "#{@layer.id}", 'lat' => @place.lat, 'lon' => @place.lon, 'action' => 'edit' }}
  = link_to map_layer_url(@map,@layer), :class=>"close-button small", "aria-label"=>"Close back",:type=>"button" do
    %span{"aria-hidden"=>"true"}
      %i.fi.fi-x.fi-30
  = render 'form_edit_clone'

app/views/places/index.html.haml
- content_for(:title) { "Places of #{@layer.title}" }


#table-wrapper
  %p.text-right.close_link_wrapper
    = link_to map_layer_url(@map,@layer), :class=>"close-link", "aria-label"=>"Close back" do
      %span{"aria-hidden"=>"true"}
        %i.fi.fi-x
  %h1
    = link_to map_path(@layer.map) do
      = @layer.map.title
    —
    = link_to map_layer_path(@layer.map,@layer) do
      = @layer.title
    %span.shy (with #{@layer.places.count} Places)

  %p
    &nbsp;        
  .grid-x.grid-padding-x
    .medium-7.cell.card
      %p.text-left.hint-simple
        - if @layer.published
          %i.fi-eye.fi-18
          This content of this layer is visible to the public
        - else
          %i.fi-lock.fi-18
          The content of this layer is not public
      - if @map.enable_time_slider
        %p.text-left.hint-simple
          %i.fi-clock.fi-18
          The time slider for this layer is activated    
      %p.text-left.hint-simple
        Privacy settings for this layer:
      %ul.hint
        %li
          - if @layer.exif_remove
            %i.fi-check.fi-18
            All EXIF data will be removed from uploaded images
          - else
            %i.fi-alert.fi-18
            EXIF data of uploaded images will not be removed
        %li
          - if @layer.rasterize_images
            %i.fi-check.fi-18
            Images will be displayed with a halftone raster
          - else
            %i.fi-alert.fi-18
            All images will be displayed unchanged
      %p.text-left.hint-simple
        You can change these settings
        = link_to edit_map_layer_path(@map,@layer) do
          in the edit mode
        %br
        %br
    .medium-5.cell
      %ul.hint
        %li
          = link_to annotations_map_layer_path(@map,@layer) do
            List of all annotations (about Places)
        %li
          = link_to relations_map_layer_path(@map,@layer) do
            List of all relations (between places)
        %li
          = link_to images_map_layer_path(@map,@layer) do
            List of all images
      %hr
      %p
        = link_to import_map_layer_path(@map,@layer), :class=>'button small' do
          %i.fi-upload.fi-18          
          Import/update places from CSV
  %p
    &nbsp;
  - if @map.enable_time_slider
    %table#timeline-list
      %thead
        %tr
          %th#timeline-list-header{colspan:2}
            %p
              - minyear = @places.reject { |place| place.startdate.nil? }.min_by { |place| place.startdate.year }&.startdate&.year || Date.today.year
              - maxyear = @places.reject { |place| place.enddate.nil? }.max_by { |place| place.enddate.year }&.enddate&.year || Date.today.year
              %b
                Timeline coverage
              from
              = minyear
              - if minyear != maxyear
                \—
                = maxyear
              - timespan = maxyear-minyear+1
              (#{timespan} #{timespan > 1 ? 'years' : 'year'})
              >>
        %tr
          %th#timeline-list-info{colspan:2}            
            %p
              %label.small
                Displays the "coverage" of all start/enddates in this layer. Dates in brackets are the new fuzzy dates with qualifiers (this replaces the fixed date format)
                %i.fi.fi-info{"data-tooltip"=>true, :title=>"This is a new feature to allow to define fuzzy dates, where either the start or end is not exactly known. You have to set a qualifier in the edit form of each place to use this feature."}
      %tbody#timeline-list-body      
        - @places.sort_by{ |e| e.startdate.nil? ? Date.new : e.startdate }.each do |place|
          %tr 
            %td
              %p
                = smart_date_display(place.startdate, place.enddate)
                - if place.startdate_qualifier.present? || place.enddate_qualifier.present?
                  %br
                  %label.small
                    (#{smart_date_display_with_qualifier(place.startdate, place.enddate, place.startdate_qualifier, place.enddate_qualifier)})
                  %br
                %em
                  = place.title
                = link_to edit_map_layer_place_path(place.layer.map,place.layer,place), 
                  :class => "",
                  :title => "Edit this place" do
                  %i.fi-pencil

            %td.nobr
              - for i in minyear..maxyear
                - if place.startdate && place.startdate.year == i
                  %span.time.time-first>‒
                - elsif place.startdate && place.startdate.year < i && place.enddate && place.enddate.year > i
                  %span.time.time-on>‒
                - else
                  %span.time.time-off>‒
  

  .grid-x
    .medium-6.cell
      Showing #{@places.count} of total of #{@layer.places.count} Placves
    .medium-6.call
      = paginate @places
  %table
    %thead
      %tr
        %th Place
        %th
          &nbsp;

    %tbody
      - @places.sort_by{ |e| e.startdate.nil? ? Date.new(9999) : e.startdate }.each do |place|
        %tr.place{"data-startyear":(place.startdate ? place.startdate.year : ''),"data-endyear":(place.enddate ? place.enddate.year : '')}
          %td
            = render 'places/list/place', place: place
          %td
            = link_to edit_map_layer_place_path(place.layer.map,place.layer,place), :class => "button small" do
              %i.fi-pencil.fi-21
              Edit
            %br
            - images = Image.where(place_id: place.id)
            - if images.count > 0
              %i.fi-photo.fi-21
              = images.count
              Images
              %br
            - videos = Video.where(place_id: place.id)
            - if videos.count > 0
              %i.fi-projection-screen.fi-21
              = videos.count
              Videos
              %br
            = link_to new_map_layer_place_image_path(place.layer.map,place.layer,place), :class => "button small" do
              %i.fi-plus.fi-21
              Image
            %br
            = link_to new_map_layer_place_video_path(place.layer.map,place.layer,place), :class => "button small" do
              %i.fi-plus.fi-21
              Video
            - if admin? && current_user.group.title == 'Admins'
              %br
              = link_to clone_map_layer_place_path(place.layer.map,place.layer,place), :class => 'button small secondary', :title=>'Make a copy of this place and edit' do
                %i.fi-page-copy.fi-21
                Copy
            %br
            - if place.images.count > 0 || place.videos.count > 0
              - warning = 'Are you sure to delete this place and all attached images and/or videos?'
            - else
              - warning = 'Are you sure to delete this place?'
            = link_to map_layer_place_path(place.layer.map,place.layer,place), method: :delete, data: { confirm:warning }, :class => "button alert small" do
              %i.fi-trash.fi-21
              Destroy
  %p.text-right= paginate @places

app/views/places/new.html.haml
#form-wrapper.large-wrapper{:data => { 'url' => "/maps/#{@map.id}/layers/#{@layer.id}/places/#{@place.id}.json", 'map_id' => "#{@map.id}", 'layer_id' => "#{@layer.id}", 'lat' => @place.lat, 'lon' => @place.lon, 'action' => 'new' }}
  = link_to map_layer_url(@map,@layer), :class=>"close-button small", "aria-label"=>"Close back",:type=>"button" do
    %span{"aria-hidden"=>"true"}
      %i.fi.fi-x.fi-30
  = render 'form'

app/views/places/show.html.haml
- content_for(:title) { "#{@place.title} — #{@place.layer.title}" }

#info-wrapper{:data => { 'url' => "/maps/#{@map.id}/layers/#{@layer.id}/places/#{@place.id}.json", 'map_id' => "#{@map.id}", 'layer_id' => "#{@layer.id}" }}

  %p.text-right.close_link_wrapper
    = link_to map_layer_url(@map,@layer), :class=>"close-link", "aria-label"=>"Close back" do
      %span{"aria-hidden"=>"true"}
        %i.fi.fi-x

  .grid-x.grid-padding-x
    - images = Image.sorted_by_place(@place.id)
    - if images.count > 0
      - textcol = 8
      .cell.small-12.medium-12
        
        .orbit{"data-orbit":true}
          .orbit-wrapper
            .orbit-controls
              %button.orbit-previous
                %span.show-for-sr
                  Previous slide
                &#9664;&#xFE0E;
              %button.orbit-next
                %span.show-for-sr
                  Next slide
                &#9654;&#xFE0E;
            %ul.orbit-container          
              - images.each do |img|
                - if img.attached?
                  - filename = ActiveStorage::Blob.service.path_for(img.key)
                  - if File.exist?(filename)
                    - if img.preview.present?
                      %li.orbit-slide{"data-open": "reveal#{img.id}"}
                        %figure.orbit-figure
                          - if img.place.layer.rasterize_images && img.itype == 'image'
                            = image_tag(img.file.variant(resize: "1000x1000", "ordered-dither": "h8x8a").processed, class: "orbit-image", alt: img.alt )
                          - else
                            = image_tag(img.file.variant(resize: "1200x1200").processed, class: "orbit-image", alt: img.alt)

                    - else
                      %li.orbit-slide{"data-open": "reveal#{img.id}"}
                        %figure.orbit-figure
                          - if img.place.layer.rasterize_images && img.itype == 'image'
                            = image_tag(img.file.variant(resize: "1000x1000", "ordered-dither": "h8x8a").processed, class: "orbit-image", alt: img.alt)
                          - else
                            = image_tag(img.file.variant(resize: "1200x1200").processed, class: "orbit-image", alt: img.alt )

                  - else
                    %p
                      No image uploaded, please do so

          - images.each do |img|
            .reveal{id: "reveal#{img.id}", "data-reveal": true, "data-animation-in": "fade-in", "data-animation-out": "fade-out"}
              - if img.file.attached?
                - filename = ActiveStorage::Blob.service.path_for(img.key)
                - if File.exist?(filename)
                  - if img.place.layer.rasterize_images && img.itype == 'image'
                    = image_tag img.file.variant(resize: "1000x1000", "ordered-dither": "h8x8a").processed, alt: img.alt
                  - else
                    = image_tag img.file.variant(resize: "1200x1200").processed, alt: img.alt

                  %button.close-button{"data-close": true, "aria-label": "Close", type: "button"}
                    %i.fi.fi-x{"aria-hidden": true}
              - else
                %p
                  No image uploaded, please do so
    - videos = Video.where(place_id: @place.id)
    - if videos.count > 0
      - textcol = 8
      .cell.small-4.medium-4
        %div
          - videos.each do |video|
            - if video.file.attached?
              - if video.preview.present?
                %p{"data-open": "reveal#{video.id}"}
                  = video_tag video.file.variant(resize: "300x300").processed
              - else
                %p{"data-open": "reveal#{video.id}"}
                  = video_tag url_for(video.file), controls: true, width:150
    - else
      - textcol = 12
    .cell{class: "small-#{textcol} medium-#{textcol}"}
      %p.hint.text-left
        = link_to map_url(@place.layer.map) do
          = @place.layer.map.title
        \—
        = link_to map_layer_url(@place.layer.map,@place.layer) do
          = @place.layer.title

      %p.date
        = smart_date_display_with_qualifier(@place.startdate, @place.enddate, @place.startdate_qualifier, @place.enddate_qualifier)
      %h1
        - if @place.uid.present?
          = @place.uid
          \&mdash;
        = @place.title
        = link_to edit_map_layer_place_path(@place.layer.map,@place.layer,@place.id) do
          %i.fi.fi-pencil.fi-24
      - if @place.subtitle.present?
        %p
          = @place.subtitle
      - if @place.teaser.present?
        %div
          %strong
            =h @place.teaser.html_safe
      - if @place.text.present?
        %div
          =h @place.text.html_safe
      %p
        - if @place.link
          = link_to @place.link, target: '_blank' do
            = @place.link
      - if @place.audio.attached?
        %p
          = audio_tag rails_blob_url(@place.audio), autoplay: true, controls: true
          = link_to @place.audio.filename, rails_blob_path(@place.audio, disposition: "attachment")

      - if @place.tag_list
        %hr.small
        %p
          - @place.tags.each do |tag|
            %span.label.secondary.tag
              = link_to map_path(@map,tag: tag.name) do
                %i.fi-price-tag
                = tag

   
      %p
        %i.fi-marker.fi-21 
        #{@place.location} #{@place.address}, #{@place.zip} #{@place.city}
      - if @place.sources.present?
        %label Sources
        %hr.small
        =h @place.sources.html_safe               
      %label Annotations
      %hr.small
      = render 'places/list/annotations'
      %p
        = link_to new_annotation_path(place_id: @place.id), class: 'button' do
          %i.fi.fi-plus
          - if @place.annotations.count > 0
            Add another annotation
          - else
            Add an annotation
      %hr.small
      - if @place.relations_from_ids
        %label Relations
        - @place.relations_froms.each do |r|
          %p
            \⟶
            = r.relation_to.layer.title
            \:
            = link_to map_layer_place_url(r.relation_to.layer.map, r.relation_to.layer, r.relation_to) do
              = r.relation_to.title
            = link_to edit_map_relation_path(@map,r), class: "button small rounded" do
              %i.fi.fi-pencil
              Edit
      %p
        = link_to new_map_relation_path(map_id: @place.layer.map.id, relations_from_id: @place.id), class: 'button' do
          %i.fi.fi-plus
          Add a relation to another place


      %p.hint.text-left
        %b Coordinates:
        #{@place.lat[0..5]}, #{@place.lon[0..5]}
        %b Published:
        - if @place.published
          %i.fi-check.fi-18
        - else
          %i.fi-lock.fi-18
        \|
        %b Last edit:
        = l(@place.updated_at)